# Generated by Django 3.1.3 on 2020-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='someTips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
