# Generated by Django 3.1.3 on 2020-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
