# Generated by Django 3.1.3 on 2020-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('speed', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startStation', models.CharField(max_length=100)),
                ('endStation', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('totalTime', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('backkups', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
