# Generated by Django 3.1.3 on 2020-12-01 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('speed', '0004_auto_20201128_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='backkups',
        ),
    ]
