# Generated by Django 3.1.3 on 2020-12-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('speed', '0005_remove_tickets_backkups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='leftTicket',
            field=models.IntegerField(default=100),
        ),
    ]
