# Generated by Django 3.1.3 on 2020-12-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('speed', '0006_tickets_leftticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10)),
                ('u_password', models.CharField(max_length=255)),
                ('u_ticket', models.CharField(max_length=30, null=True)),
                ('u_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=10)),
                ('ticketId', models.CharField(max_length=50)),
            ],
        ),
    ]
