# Generated by Django 3.1.4 on 2020-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0008_sometips_aritcle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='ticketId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
